#include "platform/native_file_system.hpp"
#include <SDL.h>
#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <system_error>
#include <array>

namespace coverplayer::platform { namespace {
std::uint32_t be32(const unsigned char* v){return(static_cast<std::uint32_t>(v[0])<<24U)|(static_cast<std::uint32_t>(v[1])<<16U)|(static_cast<std::uint32_t>(v[2])<<8U)|v[3];}
std::uint32_t syncsafe(const unsigned char* v){return(static_cast<std::uint32_t>(v[0]&127U)<<21U)|(static_cast<std::uint32_t>(v[1]&127U)<<14U)|(static_cast<std::uint32_t>(v[2]&127U)<<7U)|(v[3]&127U);}
void utf8(std::string& out,std::uint32_t c){if(c<128)out.push_back(static_cast<char>(c));else if(c<2048){out.push_back(static_cast<char>(192|(c>>6U)));out.push_back(static_cast<char>(128|(c&63U)));}else{out.push_back(static_cast<char>(224|(c>>12U)));out.push_back(static_cast<char>(128|((c>>6U)&63U)));out.push_back(static_cast<char>(128|(c&63U)));}}
std::string text(const unsigned char* data,std::size_t size){if(size<2)return{};const auto enc=data[0];std::string out;if(enc==0||enc==3){for(std::size_t i=1;i<size&&data[i];++i){if(enc==0&&data[i]>=128)utf8(out,data[i]);else out.push_back(static_cast<char>(data[i]));}}else{bool le=false;std::size_t i=1;if(enc==1&&size>=3){le=data[1]==255&&data[2]==254;if(data[1]==255||data[1]==254)i=3;}for(;i+1<size;i+=2){auto c=static_cast<std::uint16_t>(le?(data[i]|(data[i+1]<<8U)):((data[i]<<8U)|data[i+1]));if(!c)break;utf8(out,c);}}while(!out.empty()&&(out.back()==' '||out.back()=='\0'))out.pop_back();return out;}
bool frame(const std::vector<unsigned char>& b,std::size_t start){for(std::size_t i=start;i+3<b.size();++i)if(b[i]==255&&(b[i+1]&224U)==224U&&(b[i+1]&6U)!=0&&(b[i+2]&240U)!=240U&&(b[i+2]&12U)!=12U)return true;return false;}
std::uint64_t hashString(const std::string& value){std::uint64_t h=1469598103934665603ULL;for(unsigned char c:value){h^=c;h*=1099511628211ULL;}return h;}
std::string coverFile(const std::string& media,const std::string& mime,const unsigned char* data,std::size_t size){if(size<8||size>8U*1024U*1024U)return{};char* pref=SDL_GetPrefPath("CoverPlayer","CoverPlayer");if(!pref)return{};auto dir=std::filesystem::u8path(pref)/"embedded-covers";SDL_free(pref);std::string ext=mime.find("png")!=std::string::npos?".png":".jpg";if(data[0]==137&&data[1]=='P'&&data[2]=='N'&&data[3]=='G')ext=".png";std::ostringstream name;name<<std::hex<<hashString(media)<<ext;auto target=dir/name.str();std::error_code ec;std::filesystem::create_directories(dir,ec);if(ec)return{};std::ofstream out(target,std::ios::binary|std::ios::trunc);out.write(reinterpret_cast<const char*>(data),static_cast<std::streamsize>(size));if(!out)return{};return target.u8string();}
bool relevant(const std::filesystem::path& path){auto ext=path.extension().u8string();std::transform(ext.begin(),ext.end(),ext.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return ext==".mp3"||ext==".jpg"||ext==".jpeg"||ext==".png";}
void mix(std::uint64_t& h,const std::string& value){for(unsigned char c:value){h^=c;h*=1099511628211ULL;}}
std::string fixedText(const unsigned char* data,std::size_t size){std::string value(reinterpret_cast<const char*>(data),size);while(!value.empty()&&(value.back()=='\0'||value.back()==' '))value.pop_back();return value;}
}

std::vector<DirectoryEntry> NativeFileSystem::list(const std::string& path)const{std::vector<DirectoryEntry> out;std::error_code ec;for(std::filesystem::directory_iterator it(std::filesystem::u8path(path),std::filesystem::directory_options::skip_permission_denied,ec),end;it!=end&&!ec;it.increment(ec)){const auto&e=*it;bool dir=e.is_directory(ec);ec.clear();out.push_back({e.path().filename().u8string(),e.path().u8string(),dir});}return out;}
std::string NativeFileSystem::parent(const std::string& path)const{auto value=std::filesystem::u8path(path).parent_path().u8string();return value.empty()?path:value;}
bool NativeFileSystem::directoryExists(const std::string& path)const{std::error_code ec;return std::filesystem::is_directory(std::filesystem::u8path(path),ec);}
std::string NativeFileSystem::normalizedPath(const std::string& path)const{std::error_code ec;auto value=std::filesystem::weakly_canonical(std::filesystem::u8path(path),ec);if(ec)value=std::filesystem::u8path(path).lexically_normal();return value.u8string();}
bool NativeFileSystem::isPathWithin(const std::string& root,const std::string& path)const{const auto normalizedRoot=std::filesystem::u8path(normalizedPath(root));const auto normalized=std::filesystem::u8path(normalizedPath(path));const auto relative=normalized.lexically_relative(normalizedRoot);if(relative.empty())return normalized==normalizedRoot;if(relative.is_absolute())return false;for(const auto& component:relative)if(component=="..")return false;return true;}
std::uint64_t NativeFileSystem::fingerprint(const std::string& path)const{std::uint64_t h=1469598103934665603ULL;std::error_code ec;auto root=std::filesystem::u8path(path);std::vector<std::string> records;for(std::filesystem::recursive_directory_iterator it(root,std::filesystem::directory_options::skip_permission_denied,ec),end;it!=end&&!ec;it.increment(ec)){if(!it->is_regular_file(ec)||!relevant(it->path())){ec.clear();continue;}auto record=it->path().lexically_relative(root).u8string()+"|"+std::to_string(it->file_size(ec));ec.clear();record+="|"+std::to_string(it->last_write_time(ec).time_since_epoch().count());ec.clear();records.push_back(std::move(record));}std::sort(records.begin(),records.end());for(const auto& record:records)mix(h,record);return h;}
MediaMetadata NativeFileSystem::metadata(const std::string& path)const{MediaMetadata meta;std::ifstream in(std::filesystem::u8path(path),std::ios::binary);if(!in){meta.valid=false;return meta;}std::vector<unsigned char>b(10);in.read(reinterpret_cast<char*>(b.data()),10);if(in.gcount()<10){meta.valid=false;return meta;}std::size_t tagEnd=0;if(b[0]=='I'&&b[1]=='D'&&b[2]=='3'&&(b[3]==3||b[3]==4)){auto version=b[3];auto tagSize=syncsafe(b.data()+6);if(tagSize<=8U*1024U*1024U){b.resize(10+tagSize+65536);in.read(reinterpret_cast<char*>(b.data()+10),static_cast<std::streamsize>(tagSize+65536));b.resize(10+static_cast<std::size_t>(std::max<std::streamsize>(0,in.gcount())));tagEnd=std::min(b.size(),10+static_cast<std::size_t>(tagSize));for(std::size_t pos=10;pos+10<=tagEnd;){std::string id(reinterpret_cast<const char*>(b.data()+pos),4);if(id[0]=='\0')break;auto size=version==4?syncsafe(b.data()+pos+4):be32(b.data()+pos+4);auto content=pos+10;if(!size||content+size>tagEnd)break;auto* data=b.data()+content;if(id=="TIT2")meta.title=text(data,size);else if(id=="TPE1")meta.artist=text(data,size);else if(id=="TALB")meta.album=text(data,size);else if(id=="TRCK"){try{meta.trackNumber=std::stoi(text(data,size));}catch(...){meta.trackNumber=0;}}else if(id=="APIC"&&meta.embeddedCoverPath.empty()&&size>4){std::size_t cursor=1,mimeEnd=cursor;while(mimeEnd<size&&data[mimeEnd])++mimeEnd;if(mimeEnd<size){std::string mime(reinterpret_cast<const char*>(data+cursor),mimeEnd-cursor);cursor=mimeEnd+2;bool wide=data[0]==1||data[0]==2;while(cursor+(wide?1:0)<size){if(data[cursor]==0&&(!wide||data[cursor+1]==0)){cursor+=wide?2:1;break;}cursor+=wide?2:1;}if(cursor<size)meta.embeddedCoverPath=coverFile(path,mime,data+cursor,size-cursor);}}pos=content+size;}}}else{b.resize(65536);in.read(reinterpret_cast<char*>(b.data()+10),static_cast<std::streamsize>(b.size()-10));b.resize(10+static_cast<std::size_t>(std::max<std::streamsize>(0,in.gcount())));}if(meta.title.empty()||meta.artist.empty()||meta.album.empty()||meta.trackNumber==0){std::array<unsigned char,128> legacy{};in.clear();in.seekg(-static_cast<std::streamoff>(legacy.size()),std::ios::end);if(in.read(reinterpret_cast<char*>(legacy.data()),static_cast<std::streamsize>(legacy.size()))&&legacy[0]=='T'&&legacy[1]=='A'&&legacy[2]=='G'){if(meta.title.empty())meta.title=fixedText(legacy.data()+3,30);if(meta.artist.empty())meta.artist=fixedText(legacy.data()+33,30);if(meta.album.empty())meta.album=fixedText(legacy.data()+63,30);if(meta.trackNumber==0&&legacy[125]==0)meta.trackNumber=legacy[126];}}meta.valid=frame(b,tagEnd);return meta;}
}
